.TH cryptest 1 local
.SH NAME
cryptest \- Test Driver for Crypto++, a C++ Class Library of Cryptographic Primitives
.SH SYNOPSIS
.B cryptest 
[\fIOPTION\fR]
.SH DESCRIPTION
cryptest takes the following options
.TP
.B g
generate an RSA key
.TP
.B h
display usage information
.TP
.B r
encrypt and decrypt a string using RSA
.TP
.BI rs " privatekeyfile messagefile signaturefile"
sign a file using RSA
.TP
.BI rv " publickeyfile messagefile signaturefile"
verify a signature of a file using RSA
.TP
.BI m " file"
calculate MD5, SHA, and RIPEMD-160 message digests
.TP
.B t
encrypt and decrypt a string using DES-EDE in CBC mode 
.TP
.BI e|d " input output"
encrypt or decrypt a file
.TP
.BI ss " <threshold> <number-of-shares> file"
secret share a file (shares will be named file.000, file.001, etc)
.TP
.BI sr " file share1 share2 [....]"
reconstruct a secret-shared file (number of shares given must be equal
to threshold)
.TP
.BI id " <threshold> <number-of-shares> file"
information disperse a file (shares will be named file.000, file.001, etc)
.TP
.BI ir " file share1 share2 [....]"
reconstruct an information-dispersed file (number of shares given must
be equal to threshold)
.TP
.BI z " <compression-level> input output"
gzip a file
.TP
.BI u " input output"
gunzip a file
.TP
.BI ae " input output"
encrypt a file with AES in CTR mode
.TP
.BI e64 " input output"
base64 encode a file
.TP
.BI d64 " input output"
base64 decode a file
.TP
.BI e16 " input output"
hex encode a file
.TP
.BI d16 " input output"
hex decode a file
.TP
.BI ft " source-port destination-host destination-port"
forward a TCP connection
.TP
.BI fips
run the FIPS 140-2 sample application
.TP
.BI fips-rand
generate 100000 random files using FIPS Approved X.917 RNG
.TP
.BI mt " input"
run Maurer's randomness test on a file
.TP
.B v
run validation tests
.TP
.B V
display version number
.TP
.BI b " [time for each benchmark in seconds] [frequency of CPU in gigahertz]"
run benchmarks
.TP
.BI tv " filename"
run test vector file (available in TestVectors example subdirectory)
.SH AUTHOR
This man page was created by Stephen Zander, Pierre Machard and Jens
Peter Secher for the Debian distribution.  It is licenced under the
same terms as the rest of the Crypto++ library, written by Wei Dai.
